import { db } from "./index";
import { exercisesTable } from "./schema/fitness";

const exercises = [
  // ── CHEST ──────────────────────────────────────────────────────────────
  {
    name: "Barbell Bench Press",
    muscleGroup: "Chest",
    secondaryMuscles: "Triceps, Front Deltoids",
    equipment: "Barbell",
    difficulty: "Intermediate",
    instructions: "Lie flat on the bench with feet on the floor. Grip the bar slightly wider than shoulder-width. Unrack the bar and lower it to your mid-chest with control. Press the bar back up explosively until arms are fully extended. Keep your shoulder blades retracted throughout.",
  },
  {
    name: "Incline Dumbbell Press",
    muscleGroup: "Chest",
    secondaryMuscles: "Triceps, Front Deltoids",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    instructions: "Set the bench to 30–45 degrees. Hold a dumbbell in each hand at chest level with palms facing forward. Press the dumbbells up and slightly inward until arms are extended. Lower slowly back to the starting position. Focus on the upper chest stretch at the bottom.",
  },
  {
    name: "Push-Up",
    muscleGroup: "Chest",
    secondaryMuscles: "Triceps, Core, Front Deltoids",
    equipment: "Bodyweight",
    difficulty: "Beginner",
    instructions: "Start in a high plank with hands just wider than shoulder-width. Keeping your body in a straight line, lower your chest to the floor by bending your elbows. Push back up to the starting position. Keep your core braced and avoid letting your hips sag.",
  },
  {
    name: "Cable Chest Fly",
    muscleGroup: "Chest",
    secondaryMuscles: "Front Deltoids",
    equipment: "Cable Machine",
    difficulty: "Intermediate",
    instructions: "Set cables at shoulder height. Stand in the center and hold a handle in each hand. Lean slightly forward and bring your hands together in a wide arc in front of your chest. Squeeze your pecs at the midpoint, then slowly return to the start. Do not lock your elbows.",
  },
  {
    name: "Dumbbell Chest Fly",
    muscleGroup: "Chest",
    secondaryMuscles: "Front Deltoids",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    instructions: "Lie flat on a bench holding dumbbells directly above your chest with a slight bend in your elbows. Lower the dumbbells in a wide arc until you feel a stretch in your chest. Bring them back together in the same arc, squeezing the pecs at the top.",
  },
  {
    name: "Decline Barbell Bench Press",
    muscleGroup: "Chest",
    secondaryMuscles: "Triceps",
    equipment: "Barbell",
    difficulty: "Intermediate",
    instructions: "Secure your legs at the end of a decline bench. Grip the bar slightly wider than shoulder-width. Lower the bar to your lower chest with control. Press up explosively. The decline angle targets the lower chest fibers.",
  },
  {
    name: "Diamond Push-Up",
    muscleGroup: "Chest",
    secondaryMuscles: "Triceps",
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    instructions: "Form a diamond shape with your thumbs and index fingers on the floor beneath your chest. Lower your chest toward your hands, keeping elbows close to your body. Push back up. This variation increases triceps and inner chest activation.",
  },
  {
    name: "Dumbbell Pullover",
    muscleGroup: "Chest",
    secondaryMuscles: "Lats, Triceps",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    instructions: "Lie across a bench with your upper back supported. Hold one dumbbell with both hands above your chest. Lower it behind your head in an arc while keeping a slight bend in your elbows. Pull it back over your chest, squeezing at the top.",
  },

  // ── BACK ───────────────────────────────────────────────────────────────
  {
    name: "Pull-Up",
    muscleGroup: "Back",
    secondaryMuscles: "Biceps, Rear Deltoids",
    equipment: "Pull-Up Bar",
    difficulty: "Intermediate",
    instructions: "Hang from a pull-up bar with an overhand grip, hands slightly wider than shoulder-width. Engage your core and pull your chest toward the bar by driving your elbows down and back. Lower slowly until your arms are fully extended.",
  },
  {
    name: "Barbell Deadlift",
    muscleGroup: "Back",
    secondaryMuscles: "Glutes, Hamstrings, Core, Traps",
    equipment: "Barbell",
    difficulty: "Advanced",
    instructions: "Stand with feet hip-width apart, bar over mid-foot. Hinge at the hips and grip the bar just outside your legs. Keep your chest up and back flat. Drive through your heels, extending hips and knees simultaneously. Lock out at the top, then lower under control.",
  },
  {
    name: "Seated Cable Row",
    muscleGroup: "Back",
    secondaryMuscles: "Biceps, Rear Deltoids",
    equipment: "Cable Machine",
    difficulty: "Beginner",
    instructions: "Sit at a cable row machine with feet on the platform and knees slightly bent. Hold the attachment with both hands and sit upright. Pull the handle toward your lower abdomen, squeezing your shoulder blades together. Slowly extend your arms back to the start.",
  },
  {
    name: "Lat Pulldown",
    muscleGroup: "Back",
    secondaryMuscles: "Biceps, Rear Deltoids",
    equipment: "Cable Machine",
    difficulty: "Beginner",
    instructions: "Sit at a lat pulldown machine and grip the bar wider than shoulder-width. Lean back slightly and pull the bar down to your upper chest, driving your elbows toward the floor. Squeeze your lats at the bottom, then slowly return to the start.",
  },
  {
    name: "Single-Arm Dumbbell Row",
    muscleGroup: "Back",
    secondaryMuscles: "Biceps, Rear Deltoids",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    instructions: "Place one hand and knee on a bench for support. Hold a dumbbell in the other hand and let it hang. Pull the dumbbell toward your hip by driving your elbow up and back. Lower it slowly. Keep your back parallel to the floor throughout.",
  },
  {
    name: "T-Bar Row",
    muscleGroup: "Back",
    secondaryMuscles: "Biceps, Rear Deltoids",
    equipment: "Barbell",
    difficulty: "Intermediate",
    instructions: "Straddle a T-bar machine and grip the handles. Hinge forward to about 45 degrees with a flat back. Pull the bar toward your chest by driving elbows back, squeezing your shoulder blades. Lower the weight with control.",
  },
  {
    name: "Face Pull",
    muscleGroup: "Back",
    secondaryMuscles: "Rear Deltoids, Rotator Cuff",
    equipment: "Cable Machine",
    difficulty: "Beginner",
    instructions: "Attach a rope to a cable pulley at face height. Grasp both ends with an overhand grip and step back. Pull the rope toward your face while flaring your elbows out to the sides. Externally rotate your shoulders at the end. Slow and controlled throughout.",
  },
  {
    name: "Hyperextension",
    muscleGroup: "Back",
    secondaryMuscles: "Glutes, Hamstrings",
    equipment: "Bodyweight",
    difficulty: "Beginner",
    instructions: "Position yourself on a hyperextension bench with your hips at the pad edge and feet anchored. Cross your arms over your chest or clasp them behind your head. Lower your torso toward the floor, then raise it until your body forms a straight line. Do not hyperextend.",
  },
  {
    name: "Chest-Supported Row",
    muscleGroup: "Back",
    secondaryMuscles: "Biceps, Rear Deltoids",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    instructions: "Set an incline bench to 30 degrees and lie face-down on it with a dumbbell in each hand. Row the dumbbells toward your hips by driving your elbows up and back, squeezing your shoulder blades together. Lower slowly.",
  },

  // ── LEGS ───────────────────────────────────────────────────────────────
  {
    name: "Barbell Back Squat",
    muscleGroup: "Legs",
    secondaryMuscles: "Glutes, Core",
    equipment: "Barbell",
    difficulty: "Intermediate",
    instructions: "Position the bar across your upper traps and step back from the rack. Set feet shoulder-width apart, toes slightly out. Brace your core and squat down until your thighs are parallel to the floor. Drive through your heels to return to standing. Keep your chest up and knees tracking over your toes.",
  },
  {
    name: "Romanian Deadlift",
    muscleGroup: "Legs",
    secondaryMuscles: "Glutes, Lower Back",
    equipment: "Barbell",
    difficulty: "Intermediate",
    instructions: "Stand holding a barbell at hip level. Hinge at your hips, pushing them back while lowering the bar along your legs. Keep your back flat and knees slightly bent. Lower until you feel a deep hamstring stretch, then drive your hips forward to return to standing.",
  },
  {
    name: "Leg Press",
    muscleGroup: "Legs",
    secondaryMuscles: "Glutes",
    equipment: "Leg Press Machine",
    difficulty: "Beginner",
    instructions: "Sit in the leg press with your feet shoulder-width on the platform. Lower the platform by bending your knees to 90 degrees, then press back up without locking your knees at the top. Adjust foot position to target different areas — higher = more glutes, lower = more quads.",
  },
  {
    name: "Bulgarian Split Squat",
    muscleGroup: "Legs",
    secondaryMuscles: "Glutes, Core",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    instructions: "Stand two feet in front of a bench with a dumbbell in each hand. Rest your rear foot on the bench. Lower your hips until your front thigh is parallel to the floor. Press through your front heel to return. Keep your torso upright.",
  },
  {
    name: "Leg Extension",
    muscleGroup: "Legs",
    secondaryMuscles: "",
    equipment: "Leg Extension Machine",
    difficulty: "Beginner",
    instructions: "Sit on the leg extension machine with the pad resting on your lower shins. Extend your legs fully, squeezing your quads at the top. Lower slowly back to the start. Avoid locking your knees at the top.",
  },
  {
    name: "Lying Leg Curl",
    muscleGroup: "Legs",
    secondaryMuscles: "",
    equipment: "Leg Curl Machine",
    difficulty: "Beginner",
    instructions: "Lie face down on the machine with the pad behind your ankles. Curl your legs toward your glutes by bending at the knee. Squeeze your hamstrings at the top, then lower slowly. Keep your hips pressed into the pad throughout.",
  },
  {
    name: "Walking Lunge",
    muscleGroup: "Legs",
    secondaryMuscles: "Glutes, Core",
    equipment: "Bodyweight",
    difficulty: "Beginner",
    instructions: "Stand upright with feet together. Step forward with one leg and lower your back knee toward the floor. Push through your front heel to bring your rear leg forward into the next lunge. Keep your torso upright and core engaged throughout.",
  },
  {
    name: "Hip Thrust",
    muscleGroup: "Legs",
    secondaryMuscles: "Hamstrings, Core",
    equipment: "Barbell",
    difficulty: "Intermediate",
    instructions: "Sit against a bench with a barbell across your hips. Plant your feet flat and drive your hips up until your body forms a straight line from knees to shoulders. Squeeze your glutes at the top. Lower your hips back to the floor and repeat.",
  },
  {
    name: "Calf Raise",
    muscleGroup: "Legs",
    secondaryMuscles: "",
    equipment: "Bodyweight",
    difficulty: "Beginner",
    instructions: "Stand with feet hip-width apart. Rise onto the balls of your feet as high as possible. Hold briefly at the top to maximally contract your calves, then lower slowly. For more range of motion, stand on the edge of a step.",
  },
  {
    name: "Goblet Squat",
    muscleGroup: "Legs",
    secondaryMuscles: "Core, Glutes",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    instructions: "Hold a dumbbell vertically at chest height with both hands. Feet shoulder-width apart, toes slightly out. Squat down between your knees until your thighs are at least parallel to the floor. Drive through your heels to stand. Keep your chest tall.",
  },
  {
    name: "Hack Squat",
    muscleGroup: "Legs",
    secondaryMuscles: "Glutes",
    equipment: "Hack Squat Machine",
    difficulty: "Intermediate",
    instructions: "Position your shoulders and back against the pads with feet shoulder-width on the platform. Unhook the safety handles. Lower by bending your knees to 90 degrees, then press back up. Keep your lower back flat against the pad.",
  },

  // ── SHOULDERS ──────────────────────────────────────────────────────────
  {
    name: "Overhead Press",
    muscleGroup: "Shoulders",
    secondaryMuscles: "Triceps, Upper Traps",
    equipment: "Barbell",
    difficulty: "Intermediate",
    instructions: "Stand with the bar resting on your front deltoids, grip just wider than shoulder-width. Press the bar overhead until your arms are fully extended, pushing your head through as the bar clears. Lower the bar back to your shoulders with control. Keep your core braced.",
  },
  {
    name: "Dumbbell Lateral Raise",
    muscleGroup: "Shoulders",
    secondaryMuscles: "",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    instructions: "Stand with dumbbells at your sides, palms facing in. Raise your arms out to the sides until they are parallel to the floor, leading with your elbows. Keep a slight bend in your elbows. Lower slowly. Avoid swinging your torso.",
  },
  {
    name: "Dumbbell Shoulder Press",
    muscleGroup: "Shoulders",
    secondaryMuscles: "Triceps",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    instructions: "Sit on a bench with back support holding dumbbells at shoulder height, palms facing forward. Press the dumbbells up until your arms are extended overhead. Lower slowly back to shoulder height. Keep your core engaged and avoid arching your lower back.",
  },
  {
    name: "Arnold Press",
    muscleGroup: "Shoulders",
    secondaryMuscles: "Triceps, Upper Traps",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    instructions: "Start with dumbbells at shoulder height, palms facing your face. As you press upward, rotate your palms outward so they face forward at the top. Reverse the rotation as you lower the dumbbells. This rotation engages all three deltoid heads.",
  },
  {
    name: "Upright Row",
    muscleGroup: "Shoulders",
    secondaryMuscles: "Traps, Biceps",
    equipment: "Barbell",
    difficulty: "Intermediate",
    instructions: "Hold a barbell with an overhand grip, hands about shoulder-width. Pull the bar straight up along your body until it reaches chin height, flaring your elbows out to the sides. Lower slowly. Stop if you feel shoulder impingement.",
  },
  {
    name: "Cable Lateral Raise",
    muscleGroup: "Shoulders",
    secondaryMuscles: "",
    equipment: "Cable Machine",
    difficulty: "Beginner",
    instructions: "Set a cable pulley to the lowest position. Stand sideways and hold the handle with the far hand. Raise your arm out to the side until parallel to the floor. Lower slowly. The cable provides constant tension throughout the range of motion.",
  },
  {
    name: "Shrug",
    muscleGroup: "Shoulders",
    secondaryMuscles: "Traps",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    instructions: "Hold dumbbells at your sides with arms fully extended. Shrug your shoulders straight up toward your ears as high as possible. Hold briefly at the top, then lower slowly. Avoid rolling your shoulders — move straight up and down.",
  },

  // ── ARMS ───────────────────────────────────────────────────────────────
  {
    name: "Barbell Bicep Curl",
    muscleGroup: "Arms",
    secondaryMuscles: "Forearms",
    equipment: "Barbell",
    difficulty: "Beginner",
    instructions: "Stand holding a barbell with an underhand grip, hands shoulder-width apart. Curl the bar up toward your shoulders by flexing your biceps. Keep your elbows fixed at your sides. Lower slowly under control. Avoid swinging your body.",
  },
  {
    name: "Hammer Curl",
    muscleGroup: "Arms",
    secondaryMuscles: "Forearms, Brachialis",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    instructions: "Hold dumbbells with a neutral grip (palms facing each other). Curl the dumbbells up toward your shoulders while keeping your palms facing each other throughout. Lower slowly. This variation targets the brachialis and brachioradialis more than a standard curl.",
  },
  {
    name: "Tricep Dip",
    muscleGroup: "Arms",
    secondaryMuscles: "Chest, Front Deltoids",
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    instructions: "Grip parallel bars with arms extended and body upright. Lower your body by bending your elbows to about 90 degrees, keeping your torso upright. Press back up to the starting position. Lean forward slightly to involve more chest.",
  },
  {
    name: "Skull Crusher",
    muscleGroup: "Arms",
    secondaryMuscles: "",
    equipment: "Barbell",
    difficulty: "Intermediate",
    instructions: "Lie on a flat bench with a barbell held above your chest with an overhand grip. Keeping your upper arms perpendicular to the floor, bend your elbows and lower the bar toward your forehead. Extend your arms to return to the start. Control the movement throughout.",
  },
  {
    name: "Cable Tricep Pushdown",
    muscleGroup: "Arms",
    secondaryMuscles: "",
    equipment: "Cable Machine",
    difficulty: "Beginner",
    instructions: "Attach a straight bar or rope to a high cable pulley. Stand with feet shoulder-width, grip the attachment, and keep your elbows at your sides. Push the bar down until your arms are fully extended. Slowly return. Keep your upper arms still throughout.",
  },
  {
    name: "Concentration Curl",
    muscleGroup: "Arms",
    secondaryMuscles: "",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    instructions: "Sit on a bench, lean forward, and rest the back of your upper arm on your inner thigh. Curl the dumbbell up toward your shoulder. Lower slowly. Isolating the bicep in this position prevents cheating and maximizes the muscle contraction.",
  },
  {
    name: "Preacher Curl",
    muscleGroup: "Arms",
    secondaryMuscles: "",
    equipment: "Barbell",
    difficulty: "Intermediate",
    instructions: "Sit at a preacher curl bench with your upper arms resting on the angled pad. Grip the barbell with an underhand grip. Curl the bar up, squeezing the biceps at the top. Lower slowly until your arms are nearly extended. The pad prevents momentum from being used.",
  },
  {
    name: "Overhead Tricep Extension",
    muscleGroup: "Arms",
    secondaryMuscles: "",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    instructions: "Hold one dumbbell with both hands above your head. Lower the dumbbell behind your head by bending your elbows. Extend your arms back overhead, squeezing your triceps. Keep your upper arms close to your head throughout the movement.",
  },
  {
    name: "Chin-Up",
    muscleGroup: "Arms",
    secondaryMuscles: "Back, Rear Deltoids",
    equipment: "Pull-Up Bar",
    difficulty: "Intermediate",
    instructions: "Hang from a pull-up bar with an underhand grip, hands shoulder-width apart. Pull your chin above the bar by bending your elbows and driving them toward your hips. The underhand grip places more emphasis on the biceps compared to a standard pull-up. Lower slowly.",
  },

  // ── CORE ───────────────────────────────────────────────────────────────
  {
    name: "Plank",
    muscleGroup: "Core",
    secondaryMuscles: "Shoulders, Glutes",
    equipment: "Bodyweight",
    difficulty: "Beginner",
    instructions: "Start in a forearm plank position with elbows directly below your shoulders. Keep your body in a straight line from head to heels. Brace your core as if you're about to take a punch. Avoid letting your hips sag or rise. Hold for the prescribed time.",
  },
  {
    name: "Cable Crunch",
    muscleGroup: "Core",
    secondaryMuscles: "",
    equipment: "Cable Machine",
    difficulty: "Beginner",
    instructions: "Kneel below a high pulley with a rope attachment. Hold the rope behind your head. Flex your spine, crunching your abs downward until your elbows approach your knees. Squeeze the abs hard at the bottom. Slowly return, feeling the stretch in your abs.",
  },
  {
    name: "Hanging Leg Raise",
    muscleGroup: "Core",
    secondaryMuscles: "Hip Flexors",
    equipment: "Pull-Up Bar",
    difficulty: "Intermediate",
    instructions: "Hang from a pull-up bar with arms fully extended. Keeping your legs straight, raise them until they are parallel to the floor (or higher). Lower slowly with control. Avoid swinging. For easier variation, bend your knees as you raise.",
  },
  {
    name: "Russian Twist",
    muscleGroup: "Core",
    secondaryMuscles: "Obliques",
    equipment: "Bodyweight",
    difficulty: "Beginner",
    instructions: "Sit on the floor with knees bent, feet slightly raised. Lean back to a 45-degree angle. Clasp your hands or hold a weight. Rotate your torso to the right, then to the left, touching the floor beside you each time. Keep your core tight throughout.",
  },
  {
    name: "Ab Wheel Rollout",
    muscleGroup: "Core",
    secondaryMuscles: "Shoulders, Lats",
    equipment: "Ab Wheel",
    difficulty: "Advanced",
    instructions: "Kneel on the floor holding the ab wheel with both hands directly below your shoulders. Roll the wheel forward slowly until your body is nearly parallel to the floor. Pull the wheel back by contracting your abs and returning to the kneeling position. Keep your hips from sagging.",
  },
  {
    name: "Side Plank",
    muscleGroup: "Core",
    secondaryMuscles: "Obliques, Glutes",
    equipment: "Bodyweight",
    difficulty: "Beginner",
    instructions: "Lie on your side with your elbow directly below your shoulder. Raise your hips so your body forms a straight line from head to feet. Hold for the prescribed time. Keep your core braced and avoid letting your hips drop. Switch sides.",
  },
  {
    name: "Dead Bug",
    muscleGroup: "Core",
    secondaryMuscles: "",
    equipment: "Bodyweight",
    difficulty: "Beginner",
    instructions: "Lie on your back with arms pointed toward the ceiling and knees bent at 90 degrees. Slowly extend your right leg and lower your left arm toward the floor simultaneously. Return to start, then repeat with the opposite arm and leg. Keep your lower back pressed to the floor throughout.",
  },
  {
    name: "Bicycle Crunch",
    muscleGroup: "Core",
    secondaryMuscles: "Obliques",
    equipment: "Bodyweight",
    difficulty: "Beginner",
    instructions: "Lie on your back with hands behind your head and legs raised. Bring one knee toward your chest while rotating your opposite elbow to meet it. Extend the other leg. Alternate sides in a pedaling motion. Focus on the rotation — do not just move your elbows.",
  },

  // ── CARDIO ─────────────────────────────────────────────────────────────
  {
    name: "Treadmill Run",
    muscleGroup: "Cardio",
    secondaryMuscles: "Legs, Core",
    equipment: "Treadmill",
    difficulty: "Beginner",
    instructions: "Set the treadmill to your target speed and incline. Maintain an upright posture, look forward, and swing your arms naturally. Land with a midfoot strike. Start with a 5-minute warm-up walk, increase speed gradually, and cool down at the end.",
  },
  {
    name: "Rowing Machine",
    muscleGroup: "Cardio",
    secondaryMuscles: "Back, Legs, Arms",
    equipment: "Rowing Machine",
    difficulty: "Beginner",
    instructions: "Sit on the rower with feet strapped in. Grasp the handle with an overhand grip. Begin each stroke by driving your legs, then leaning back slightly, then pulling the handle to your lower chest. Reverse the motion to return. Aim for 18–24 strokes per minute for endurance.",
  },
  {
    name: "Jump Rope",
    muscleGroup: "Cardio",
    secondaryMuscles: "Calves, Shoulders",
    equipment: "Jump Rope",
    difficulty: "Beginner",
    instructions: "Hold the handles lightly at hip level. Swing the rope over your head and jump over it as it passes under your feet. Keep jumps small — just enough clearance for the rope. Land softly on the balls of your feet. Keep your core engaged and elbows close to your body.",
  },
  {
    name: "Burpee",
    muscleGroup: "Cardio",
    secondaryMuscles: "Chest, Legs, Core",
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    instructions: "Start standing. Drop your hands to the floor and jump your feet back to a push-up position. Perform a push-up. Jump your feet toward your hands, then explosively jump up with arms overhead. Land softly and immediately begin the next repetition.",
  },
  {
    name: "Stationary Bike",
    muscleGroup: "Cardio",
    secondaryMuscles: "Legs",
    equipment: "Stationary Bike",
    difficulty: "Beginner",
    instructions: "Set the seat so your knee has a slight bend at the bottom of each pedal stroke. Keep an upright posture and engage your core. Pedal at a steady cadence for steady-state cardio, or use intervals — 30 seconds hard, 1 minute easy — for HIIT.",
  },
  {
    name: "Mountain Climber",
    muscleGroup: "Cardio",
    secondaryMuscles: "Core, Legs",
    equipment: "Bodyweight",
    difficulty: "Beginner",
    instructions: "Start in a high plank position with arms straight. Drive one knee toward your chest, then quickly switch legs in a running motion. Keep your hips low and level — avoid letting them rise. Move as fast as you can while maintaining form.",
  },

  // ── FULL BODY ──────────────────────────────────────────────────────────
  {
    name: "Kettlebell Swing",
    muscleGroup: "Full Body",
    secondaryMuscles: "Glutes, Hamstrings, Core, Shoulders",
    equipment: "Kettlebell",
    difficulty: "Intermediate",
    instructions: "Stand with feet shoulder-width, kettlebell on the floor between your feet. Hinge at the hips to grab it, then hike it back between your legs. Snap your hips forward explosively to swing the bell to shoulder height. Let it swing back between your legs and repeat. Power comes from the hips, not the arms.",
  },
  {
    name: "Clean and Press",
    muscleGroup: "Full Body",
    secondaryMuscles: "Legs, Back, Shoulders, Core",
    equipment: "Barbell",
    difficulty: "Advanced",
    instructions: "Stand with feet shoulder-width, barbell on the floor. Deadlift the bar explosively, pulling it high and catching it in a front rack position at shoulder height. From there, press the bar overhead until arms are fully extended. Lower the bar back to the floor under control.",
  },
  {
    name: "Thruster",
    muscleGroup: "Full Body",
    secondaryMuscles: "Legs, Shoulders, Triceps",
    equipment: "Barbell",
    difficulty: "Advanced",
    instructions: "Hold a barbell in a front rack position at shoulder height. Perform a front squat by sitting into your hips. As you rise out of the squat, use the momentum to press the barbell overhead in one fluid motion. Lower the bar back to your shoulders and immediately squat again.",
  },
  {
    name: "Dumbbell Snatch",
    muscleGroup: "Full Body",
    secondaryMuscles: "Legs, Back, Shoulders",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    instructions: "Hold a dumbbell between your legs in a semi-squat. In one explosive movement, extend your hips and knees while pulling the dumbbell up along your body, then punch your hand upward overhead. Lock out at the top with the dumbbell directly over your shoulder. Lower under control.",
  },
  {
    name: "Box Jump",
    muscleGroup: "Full Body",
    secondaryMuscles: "Legs, Glutes, Core",
    equipment: "Plyometric Box",
    difficulty: "Intermediate",
    instructions: "Stand facing a sturdy box. Bend your knees into a half-squat and swing your arms back. Explosively jump onto the box, landing softly with bent knees in a squat position. Stand fully upright on the box. Step back down (don't jump down) and repeat.",
  },
  {
    name: "Battle Ropes",
    muscleGroup: "Full Body",
    secondaryMuscles: "Shoulders, Arms, Core",
    equipment: "Battle Ropes",
    difficulty: "Intermediate",
    instructions: "Stand holding one rope end in each hand. Alternate raising and lowering each arm rapidly to create waves in the ropes. Keep your core braced, knees slightly bent, and back upright. Vary with double waves (both arms together), circles, or slams for different stimulus.",
  },
];

async function seed() {
  console.log(`Seeding ${exercises.length} exercises...`);

  const existing = await db.select({ id: exercisesTable.id }).from(exercisesTable).limit(1);
  if (existing.length > 0) {
    console.log("Exercises already seeded. Skipping.");
    process.exit(0);
  }

  await db.insert(exercisesTable).values(exercises);
  console.log(`✓ Inserted ${exercises.length} exercises successfully.`);
  process.exit(0);
}

seed().catch(err => {
  console.error("Seed failed:", err);
  process.exit(1);
});
