import { db } from "@workspace/db";
import { exercisesTable } from "@workspace/db/schema";
import { sql } from "drizzle-orm";

const exercises = [
  // ─── CHEST ───────────────────────────────────────────────────────────────
  { name: "Barbell Bench Press", muscleGroup: "Chest", secondaryMuscles: "Triceps, Front Delts", equipment: "Barbell", difficulty: "Intermediate", instructions: "Lie flat on bench. Grip bar slightly wider than shoulder-width. Lower bar to mid-chest with control. Press bar back up to full extension. Keep wrists straight and feet flat on floor." },
  { name: "Incline Dumbbell Press", muscleGroup: "Chest", secondaryMuscles: "Front Delts, Triceps", equipment: "Dumbbells", difficulty: "Intermediate", instructions: "Set bench to 30-45 degrees. Hold dumbbells at chest level. Press up and slightly inward. Lower slowly with full stretch. Keep core tight throughout." },
  { name: "Decline Barbell Press", muscleGroup: "Chest", secondaryMuscles: "Triceps, Lower Chest", equipment: "Barbell", difficulty: "Intermediate", instructions: "Secure feet on decline bench. Grip bar just outside shoulder-width. Lower to lower chest. Press explosively to lockout. Keep chest up and shoulders back." },
  { name: "Cable Chest Flyes", muscleGroup: "Chest", secondaryMuscles: "Front Delts", equipment: "Cable Machine", difficulty: "Beginner", instructions: "Stand in center of cable machine. Hold handles at chest height. Bring hands together in arc motion. Squeeze chest hard at peak. Return slowly with control." },
  { name: "Dips (Chest Emphasis)", muscleGroup: "Chest", secondaryMuscles: "Triceps, Shoulders", equipment: "Dip Bars", difficulty: "Intermediate", instructions: "Grip parallel bars. Lean forward 30 degrees. Lower until upper arms are parallel to ground. Push up through chest, not just arms. Keep elbows flared slightly out." },
  { name: "Push-Ups", muscleGroup: "Chest", secondaryMuscles: "Triceps, Core", equipment: "Bodyweight", difficulty: "Beginner", instructions: "Start in plank position. Lower chest to floor by bending elbows. Push back up explosively. Keep body in straight line throughout. Squeeze chest at top." },
  { name: "Pec Deck Machine", muscleGroup: "Chest", secondaryMuscles: "Front Delts", equipment: "Machine", difficulty: "Beginner", instructions: "Sit with back flat against pad. Place forearms on arm pads. Bring arms together in front. Squeeze chest at peak contraction. Return slowly and repeat." },
  { name: "Dumbbell Flyes", muscleGroup: "Chest", secondaryMuscles: "Front Delts", equipment: "Dumbbells", difficulty: "Beginner", instructions: "Lie flat on bench with dumbbells. Extend arms with slight bend in elbow. Lower dumbbells in wide arc until chest stretches. Reverse arc to bring them together. Do not lockout elbows." },
  { name: "Landmine Press", muscleGroup: "Chest", secondaryMuscles: "Front Delts, Triceps", equipment: "Barbell", difficulty: "Intermediate", instructions: "Secure barbell in landmine. Stand and grip end with both hands at chest. Press upward and forward at 45-degree angle. Lower slowly. Great for upper chest activation." },
  { name: "Close-Grip Bench Press", muscleGroup: "Chest", secondaryMuscles: "Triceps", equipment: "Barbell", difficulty: "Intermediate", instructions: "Grip bar with hands shoulder-width. Lower bar to lower chest. Keep elbows tucked to sides. Press through chest and triceps. Squeeze at top." },
  { name: "Incline Barbell Press", muscleGroup: "Chest", secondaryMuscles: "Front Delts, Triceps", equipment: "Barbell", difficulty: "Intermediate", instructions: "Set bench to 30-45 degrees. Grip slightly wider than shoulder-width. Lower bar to upper chest. Press explosively. Focus on upper chest squeeze." },
  { name: "Low Cable Flyes", muscleGroup: "Chest", secondaryMuscles: "Front Delts", equipment: "Cable Machine", difficulty: "Beginner", instructions: "Set cables low. Stand in split stance. Bring handles upward and together at chest height. Squeeze upper chest. Return slowly with control." },
  { name: "Svend Press", muscleGroup: "Chest", secondaryMuscles: "Triceps", equipment: "Plate", difficulty: "Beginner", instructions: "Hold weight plate between palms at chest level. Press outward squeezing plate between hands. Extend arms fully. Return to chest. Constant chest tension throughout." },
  { name: "Dumbbell Pullover", muscleGroup: "Chest", secondaryMuscles: "Lats, Serratus", equipment: "Dumbbells", difficulty: "Intermediate", instructions: "Lie across bench with upper back. Hold dumbbell with both hands above chest. Lower dumbbell behind head in arc. Bring back to start. Feel deep chest and lat stretch." },
  { name: "Weighted Push-Ups", muscleGroup: "Chest", secondaryMuscles: "Triceps, Shoulders", equipment: "Bodyweight", difficulty: "Advanced", instructions: "Start in push-up position with weight plate on back. Lower chest to floor with control. Push explosively to lockout. Keep core tight. Full range of motion." },
  { name: "Chest Press Machine", muscleGroup: "Chest", secondaryMuscles: "Triceps, Front Delts", equipment: "Machine", difficulty: "Beginner", instructions: "Adjust seat so handles align with mid-chest. Push handles outward to full extension. Squeeze chest at lockout. Return slowly. Do not let weight stack touch." },
  { name: "Incline Cable Flyes", muscleGroup: "Chest", secondaryMuscles: "Front Delts", equipment: "Cable Machine", difficulty: "Intermediate", instructions: "Set cables low. Lie on incline bench between two cable stacks. Perform flyes with constant cable tension. Squeeze upper chest. Greater range than dumbbell flyes." },
  { name: "Plyometric Push-Ups", muscleGroup: "Chest", secondaryMuscles: "Triceps, Core", equipment: "Bodyweight", difficulty: "Advanced", instructions: "Start in push-up position. Lower chest quickly then push explosively. Clap hands at top. Land softly and absorb impact. Develops power and fast-twitch fibers." },
  { name: "Resistance Band Chest Press", muscleGroup: "Chest", secondaryMuscles: "Triceps, Front Delts", equipment: "Resistance Band", difficulty: "Beginner", instructions: "Anchor band behind you at chest height. Stand and press forward. Squeeze chest at full extension. Control return under tension. Great for warm-up and pump." },
  { name: "Single-Arm Dumbbell Press", muscleGroup: "Chest", secondaryMuscles: "Triceps, Core", equipment: "Dumbbells", difficulty: "Intermediate", instructions: "Lie on bench holding one dumbbell. Press up while bracing core. Anti-rotation challenge. Switch arms after each set. Excellent for fixing muscle imbalances." },

  // ─── BACK ────────────────────────────────────────────────────────────────
  { name: "Pull-Ups", muscleGroup: "Back", secondaryMuscles: "Biceps, Rear Delts", equipment: "Pull-Up Bar", difficulty: "Intermediate", instructions: "Hang from bar with palms facing away. Pull body up until chin clears bar. Lower slowly under control. Do not swing or use momentum. Full hang at bottom." },
  { name: "Deadlift", muscleGroup: "Back", secondaryMuscles: "Glutes, Hamstrings, Traps", equipment: "Barbell", difficulty: "Advanced", instructions: "Stand with bar over mid-foot. Bend and grip just outside legs. Keep back flat and chest up. Drive through floor and stand up. Lock hips at top. Lower with control." },
  { name: "Bent-Over Barbell Row", muscleGroup: "Back", secondaryMuscles: "Biceps, Rear Delts", equipment: "Barbell", difficulty: "Intermediate", instructions: "Hinge at hips, torso parallel to floor. Grip bar slightly wider than shoulder-width. Pull bar to lower ribcage. Squeeze shoulder blades together at top. Lower slowly." },
  { name: "Lat Pulldown", muscleGroup: "Back", secondaryMuscles: "Biceps, Rear Delts", equipment: "Cable Machine", difficulty: "Beginner", instructions: "Grip bar wider than shoulder-width. Lean back slightly. Pull bar to upper chest, driving elbows down. Squeeze lats at bottom. Return bar with control." },
  { name: "Seated Cable Row", muscleGroup: "Back", secondaryMuscles: "Biceps, Rear Delts", equipment: "Cable Machine", difficulty: "Beginner", instructions: "Sit with knees slightly bent. Hold handle and pull to abdomen. Drive elbows back past torso. Squeeze shoulder blades. Return with full arm extension." },
  { name: "T-Bar Row", muscleGroup: "Back", secondaryMuscles: "Biceps, Rear Delts", equipment: "Barbell", difficulty: "Intermediate", instructions: "Straddle landmine barbell. Hinge at hips with flat back. Pull bar to lower chest using handles. Drive elbows back hard. Lower with control. Heavy compound movement." },
  { name: "Single-Arm Dumbbell Row", muscleGroup: "Back", secondaryMuscles: "Biceps, Rear Delts", equipment: "Dumbbells", difficulty: "Beginner", instructions: "Brace knee and hand on bench. Hold dumbbell in free hand. Row to hip, driving elbow behind you. Squeeze lat at top. Lower slowly. Keep back flat." },
  { name: "Face Pulls", muscleGroup: "Back", secondaryMuscles: "Rear Delts, Rotator Cuff", equipment: "Cable Machine", difficulty: "Beginner", instructions: "Set cable at head height with rope attachment. Pull rope toward face with elbows high. Externally rotate at end. Squeeze rear delts. Return slowly." },
  { name: "Chin-Ups", muscleGroup: "Back", secondaryMuscles: "Biceps", equipment: "Pull-Up Bar", difficulty: "Intermediate", instructions: "Hang with palms facing you. Pull body up until chin clears bar. Squeeze biceps and lats at top. Lower with control. Great bicep and lat developer." },
  { name: "Good Mornings", muscleGroup: "Back", secondaryMuscles: "Hamstrings, Glutes", equipment: "Barbell", difficulty: "Intermediate", instructions: "Place barbell on upper back. Stand with feet shoulder-width. Hinge at hips with slight knee bend. Lower until torso is parallel. Drive hips forward to stand." },
  { name: "Hyperextensions", muscleGroup: "Back", secondaryMuscles: "Glutes, Hamstrings", equipment: "Machine", difficulty: "Beginner", instructions: "Lock legs in hyperextension machine. Fold forward at waist. Rise up until body is straight. Squeeze glutes at top. Controlled movement throughout." },
  { name: "Meadows Row", muscleGroup: "Back", secondaryMuscles: "Biceps, Rear Delts", equipment: "Barbell", difficulty: "Advanced", instructions: "Stand perpendicular to landmine barbell. Use staggered stance. Row barbell to hip with overhand grip. Drive elbow up and back. Squeeze at top. Excellent lat stretch." },
  { name: "Rack Pulls", muscleGroup: "Back", secondaryMuscles: "Traps, Glutes", equipment: "Barbell", difficulty: "Advanced", instructions: "Set safety bars at knee height. Lift bar as in deadlift top half. Excellent for building trap and upper back thickness. Handle supramaximal loads safely." },
  { name: "Pendlay Row", muscleGroup: "Back", secondaryMuscles: "Biceps, Rear Delts", equipment: "Barbell", difficulty: "Intermediate", instructions: "Start each rep with bar on floor. Torso parallel to floor. Explode bar to torso. Return to floor each rep. Develops explosive back strength." },
  { name: "Wide-Grip Lat Pulldown", muscleGroup: "Back", secondaryMuscles: "Biceps", equipment: "Cable Machine", difficulty: "Beginner", instructions: "Grip bar 1.5x shoulder-width. Lean back 30 degrees. Pull bar to upper chest. Drive elbows down and back. Excellent for width and V-taper." },
  { name: "Straight-Arm Pulldown", muscleGroup: "Back", secondaryMuscles: "Triceps long head", equipment: "Cable Machine", difficulty: "Beginner", instructions: "Stand at cable machine. Keep arms nearly straight. Pull bar down to thighs in arc motion. Squeeze lats hard at bottom. Isolates lats from biceps." },
  { name: "Inverted Row (Australian Pull-Up)", muscleGroup: "Back", secondaryMuscles: "Biceps, Rear Delts", equipment: "Barbell", difficulty: "Beginner", instructions: "Hang under a bar at waist height. Keep body straight. Pull chest to bar driving elbows back. Squeeze at top. Easier progression to pull-ups." },
  { name: "Barbell Shrugs", muscleGroup: "Back", secondaryMuscles: "Traps, Neck", equipment: "Barbell", difficulty: "Beginner", instructions: "Hold barbell in front. Shrug shoulders straight up toward ears. Hold 1 second at top. Lower slowly. Do not roll shoulders, straight up and down." },
  { name: "Cable Pullover", muscleGroup: "Back", secondaryMuscles: "Serratus, Chest", equipment: "Cable Machine", difficulty: "Intermediate", instructions: "Kneel in front of high cable. Hold bar overhead. Pull bar down in arc to thighs. Squeeze lats at bottom. Return with control. Constant tension on lats." },
  { name: "Renegade Row", muscleGroup: "Back", secondaryMuscles: "Biceps, Core", equipment: "Dumbbells", difficulty: "Advanced", instructions: "Start in push-up position with dumbbells. Row one dumbbell while stabilizing with other arm. Minimize rotation by bracing core. Alternate arms. Challenging anti-rotation row." },

  // ─── LEGS ────────────────────────────────────────────────────────────────
  { name: "Barbell Back Squat", muscleGroup: "Legs", secondaryMuscles: "Glutes, Core, Lower Back", equipment: "Barbell", difficulty: "Intermediate", instructions: "Bar on upper back traps. Feet shoulder-width. Squat down until thighs parallel or below. Drive through heels to stand. Keep knees tracking over toes." },
  { name: "Romanian Deadlift (RDL)", muscleGroup: "Legs", secondaryMuscles: "Glutes, Lower Back", equipment: "Barbell", difficulty: "Intermediate", instructions: "Hold barbell at hips. Push hips back while keeping bar close to legs. Lower until deep hamstring stretch. Drive hips forward to stand. Keep back flat." },
  { name: "Leg Press", muscleGroup: "Legs", secondaryMuscles: "Glutes", equipment: "Machine", difficulty: "Beginner", instructions: "Set feet shoulder-width on platform. Lower weight by bending knees to 90 degrees. Press through entire foot. Do not lock knees at top. Control the descent." },
  { name: "Bulgarian Split Squat", muscleGroup: "Legs", secondaryMuscles: "Glutes, Hip Flexors", equipment: "Dumbbells", difficulty: "Intermediate", instructions: "Rear foot elevated on bench. Hold dumbbells at sides. Lower back knee toward floor. Front knee tracks over toe. Drive through front heel to stand. One of the best leg builders." },
  { name: "Lunges", muscleGroup: "Legs", secondaryMuscles: "Glutes, Core", equipment: "Dumbbells", difficulty: "Beginner", instructions: "Step forward into lunge. Lower back knee to floor. Front knee over ankle. Push through front heel to return. Alternate legs or walk forward." },
  { name: "Leg Extension", muscleGroup: "Legs", secondaryMuscles: "Quads", equipment: "Machine", difficulty: "Beginner", instructions: "Sit in machine with pad on lower shins. Extend legs to full lockout. Squeeze quads hard at top. Lower slowly, do not let weight stack drop. Quad isolation." },
  { name: "Leg Curl (Seated)", muscleGroup: "Legs", secondaryMuscles: "Hamstrings, Calves", equipment: "Machine", difficulty: "Beginner", instructions: "Sit with leg pad on lower leg. Curl legs down as far as possible. Squeeze hamstrings at full contraction. Return slowly. Better than lying for hip flexion." },
  { name: "Standing Calf Raises", muscleGroup: "Legs", secondaryMuscles: "Soleus", equipment: "Machine", difficulty: "Beginner", instructions: "Stand with balls of feet on platform. Rise onto toes as high as possible. Hold 1 second. Lower until heel stretches below platform. Full range is essential." },
  { name: "Hack Squat", muscleGroup: "Legs", secondaryMuscles: "Glutes", equipment: "Machine", difficulty: "Intermediate", instructions: "Position shoulders on machine pads. Feet shoulder-width low on platform. Squat down until thighs parallel. Press through heels to extend. Keep lower back against pad." },
  { name: "Sumo Deadlift", muscleGroup: "Legs", secondaryMuscles: "Glutes, Inner Thigh, Back", equipment: "Barbell", difficulty: "Advanced", instructions: "Wide stance with toes pointed out 45 degrees. Grip bar inside legs. Keep chest up. Drive hips through and stand tall. Great for glutes and inner thighs." },
  { name: "Box Jump", muscleGroup: "Legs", secondaryMuscles: "Glutes, Core", equipment: "Plyo Box", difficulty: "Intermediate", instructions: "Stand in front of box. Dip down and swing arms. Jump onto box, landing softly in squat position. Stand fully. Step down carefully. Develops explosive leg power." },
  { name: "Goblet Squat", muscleGroup: "Legs", secondaryMuscles: "Glutes, Core", equipment: "Dumbbell", difficulty: "Beginner", instructions: "Hold dumbbell vertically at chest. Feet shoulder-width with toes out. Squat deep, keeping chest upright. Push knees out. Drive through heels to stand." },
  { name: "Glute-Ham Raise", muscleGroup: "Legs", secondaryMuscles: "Glutes, Lower Back", equipment: "Machine", difficulty: "Advanced", instructions: "Lock feet in GHR machine. Start upright. Lower body forward using hamstrings. Use hamstrings to curl back up. Extremely demanding posterior chain exercise." },
  { name: "Sissy Squat", muscleGroup: "Legs", secondaryMuscles: "Quads", equipment: "Bodyweight", difficulty: "Intermediate", instructions: "Hold support for balance. Lean backward as you bend knees. Lower until thighs are below parallel. Rise back to starting position. Extreme quad isolation." },
  { name: "Nordic Curl", muscleGroup: "Legs", secondaryMuscles: "Hamstrings", equipment: "Bodyweight", difficulty: "Advanced", instructions: "Anchor feet. Start tall on knees. Lower body forward as slowly as possible using hamstrings. Catch with hands. Push back to start. Best hamstring eccentric exercise." },
  { name: "Farmer's Walk", muscleGroup: "Legs", secondaryMuscles: "Traps, Core, Forearms", equipment: "Dumbbells", difficulty: "Intermediate", instructions: "Hold heavy dumbbells at sides. Walk with tall posture and tight core. Short powerful steps. Works entire body with emphasis on legs and grip strength." },
  { name: "Front Squat", muscleGroup: "Legs", secondaryMuscles: "Core, Upper Back", equipment: "Barbell", difficulty: "Advanced", instructions: "Bar on front delts with elbows high. Squat deep keeping torso upright. Drive elbows up to keep bar secure. Rise through heels. More quad dominant than back squat." },
  { name: "Step-Ups", muscleGroup: "Legs", secondaryMuscles: "Glutes, Balance", equipment: "Dumbbells", difficulty: "Beginner", instructions: "Stand in front of bench or box. Step up with one foot, drive knee up. Stand fully on box. Return slowly. Excellent unilateral leg developer." },
  { name: "Lying Leg Curl", muscleGroup: "Legs", secondaryMuscles: "Hamstrings", equipment: "Machine", difficulty: "Beginner", instructions: "Lie face down on machine. Curl legs toward glutes as far as possible. Squeeze hamstrings at peak. Lower slowly. Keep hips pressed down on pad." },
  { name: "Seated Calf Raise", muscleGroup: "Legs", secondaryMuscles: "Soleus", equipment: "Machine", difficulty: "Beginner", instructions: "Sit with pad on lower thighs above knees. Rise onto toes as high as possible. Hold 1 second at top. Lower for full stretch. Targets soleus more than standing variation." },

  // ─── SHOULDERS ───────────────────────────────────────────────────────────
  { name: "Overhead Press (OHP)", muscleGroup: "Shoulders", secondaryMuscles: "Triceps, Upper Traps", equipment: "Barbell", difficulty: "Intermediate", instructions: "Hold barbell at collar bone. Press bar directly overhead. Lock elbows at top. Lower back to collar bone with control. Keep core braced throughout." },
  { name: "Dumbbell Lateral Raises", muscleGroup: "Shoulders", secondaryMuscles: "Upper Traps", equipment: "Dumbbells", difficulty: "Beginner", instructions: "Stand with dumbbells at sides. Raise arms to shoulder height in arc. Lead with elbows not hands. Lower slowly to fully stretch delts. Keep slight bend in elbow." },
  { name: "Arnold Press", muscleGroup: "Shoulders", secondaryMuscles: "Triceps, Front Delts", equipment: "Dumbbells", difficulty: "Intermediate", instructions: "Start with dumbbells at shoulder height, palms facing you. Press up while rotating palms forward. Return by reversing rotation. Works all three delt heads through rotation." },
  { name: "Rear Delt Flyes", muscleGroup: "Shoulders", secondaryMuscles: "Rhomboids, Traps", equipment: "Dumbbells", difficulty: "Beginner", instructions: "Bend at 90 degrees. Hold dumbbells under chest. Raise arms in arc to sides at shoulder height. Squeeze rear delts. Lower slowly. Elbows slightly bent throughout." },
  { name: "Upright Rows", muscleGroup: "Shoulders", secondaryMuscles: "Traps, Biceps", equipment: "Barbell", difficulty: "Intermediate", instructions: "Hold barbell at hips, overhand grip. Pull bar straight up to chin, elbows flaring out. Hold briefly at top. Lower with control. Avoid if shoulder impingement." },
  { name: "Cable Lateral Raises", muscleGroup: "Shoulders", secondaryMuscles: "Upper Traps", equipment: "Cable Machine", difficulty: "Beginner", instructions: "Stand beside cable machine, cable at floor level. Raise arm across body to shoulder height. Constant cable tension throughout. Lower slowly. Better than dumbbells for constant tension." },
  { name: "Machine Shoulder Press", muscleGroup: "Shoulders", secondaryMuscles: "Triceps", equipment: "Machine", difficulty: "Beginner", instructions: "Adjust seat so handles are at shoulder height. Press handles overhead to full extension. Lower back to start with control. Safe, guided movement for shoulder development." },
  { name: "Dumbbell Shoulder Press", muscleGroup: "Shoulders", secondaryMuscles: "Triceps, Upper Traps", equipment: "Dumbbells", difficulty: "Beginner", instructions: "Sit or stand holding dumbbells at shoulder height. Press overhead until arms fully extended. Lower slowly to starting position. Keep core tight throughout." },
  { name: "Seated Dumbbell Lateral Raises", muscleGroup: "Shoulders", secondaryMuscles: "Upper Traps", equipment: "Dumbbells", difficulty: "Beginner", instructions: "Sit at end of bench. Raise dumbbells to side at shoulder height. Eliminates body momentum, true isolation. Perfect form is easier seated. Lower fully between reps." },
  { name: "Cable Face Pulls", muscleGroup: "Shoulders", secondaryMuscles: "Rear Delts, Rotator Cuff", equipment: "Cable Machine", difficulty: "Beginner", instructions: "Set rope at head height. Pull to face with elbows high and wide. Rotate externally at end range. Excellent for shoulder health and rear delt development." },
  { name: "Push Press", muscleGroup: "Shoulders", secondaryMuscles: "Legs, Triceps", equipment: "Barbell", difficulty: "Advanced", instructions: "Dip slightly at knees. Explosively drive bar overhead using leg drive. Lock out overhead. Lower with control. Allows heavier loads than strict press." },
  { name: "Barbell Front Raises", muscleGroup: "Shoulders", secondaryMuscles: "Chest, Traps", equipment: "Barbell", difficulty: "Beginner", instructions: "Hold barbell at hips with overhand grip. Raise bar forward to shoulder height. Control the descent. Do not swing. Isolates front deltoid." },
  { name: "Plate Front Raises", muscleGroup: "Shoulders", secondaryMuscles: "Chest", equipment: "Plate", difficulty: "Beginner", instructions: "Hold weight plate at 3 and 9 o'clock. Raise plate forward to shoulder height. Lower slowly. Constant tension through grip. Front delt isolation." },
  { name: "Landmine Shoulder Press", muscleGroup: "Shoulders", secondaryMuscles: "Triceps, Serratus", equipment: "Barbell", difficulty: "Intermediate", instructions: "Hold end of landmine barbell at shoulder. Press diagonally forward and up. Lower with control. Arc of motion is easier on shoulder joint than vertical press." },
  { name: "Dumbbell Shrugs", muscleGroup: "Shoulders", secondaryMuscles: "Traps, Neck", equipment: "Dumbbells", difficulty: "Beginner", instructions: "Hold dumbbells at sides. Shrug shoulders up toward ears. Hold 1-2 seconds. Lower fully to stretch traps. Do not roll shoulders forward or backward." },
  { name: "Reverse Pec Deck", muscleGroup: "Shoulders", secondaryMuscles: "Rear Delts, Rhomboids", equipment: "Machine", difficulty: "Beginner", instructions: "Face into machine. Grip handles in front. Drive handles back past body in wide arc. Squeeze rear delts hard. Return to front slowly. Great isolation exercise." },
  { name: "Bradford Press", muscleGroup: "Shoulders", secondaryMuscles: "Triceps", equipment: "Barbell", difficulty: "Intermediate", instructions: "Press bar from front to back in alternating motion. Move bar just over head each rep. Keeps constant tension on all three delt heads. Excellent shoulder conditioning." },
  { name: "Handstand Push-Ups", muscleGroup: "Shoulders", secondaryMuscles: "Triceps, Traps", equipment: "Bodyweight", difficulty: "Advanced", instructions: "Kick into handstand against wall. Lower head to floor by bending elbows. Press back to full extension. Extremely demanding compound shoulder exercise." },
  { name: "Cuban Press", muscleGroup: "Shoulders", secondaryMuscles: "Rotator Cuff", equipment: "Dumbbells", difficulty: "Intermediate", instructions: "Start with elbows at 90 degrees and upper arms parallel to floor. Rotate forearms up. Press overhead. Lower and reverse. Excellent rotator cuff strengthener." },
  { name: "Lu Raises", muscleGroup: "Shoulders", secondaryMuscles: "Upper Traps, Rear Delts", equipment: "Dumbbells", difficulty: "Intermediate", instructions: "Hold light dumbbells. Alternate between front raise and lateral raise each rep. Full range of motion. Trains all three heads with controlled alternating movement." },

  // ─── ARMS ────────────────────────────────────────────────────────────────
  { name: "Barbell Bicep Curls", muscleGroup: "Arms", secondaryMuscles: "Forearms, Brachialis", equipment: "Barbell", difficulty: "Beginner", instructions: "Hold barbell with underhand grip. Curl toward shoulder keeping elbows stationary. Squeeze at top. Lower with full control. Do not swing torso to lift weight." },
  { name: "Tricep Pushdowns (Cable)", muscleGroup: "Arms", secondaryMuscles: "Forearms", equipment: "Cable Machine", difficulty: "Beginner", instructions: "Grip cable bar from above at chest height. Push bar down to full extension. Squeeze triceps hard at lockout. Return bar slowly to start. Keep elbows tucked." },
  { name: "Hammer Curls", muscleGroup: "Arms", secondaryMuscles: "Brachioradialis, Forearms", equipment: "Dumbbells", difficulty: "Beginner", instructions: "Hold dumbbells with neutral grip, palms facing each other. Curl to shoulder height. Squeeze brachialis at top. Lower slowly. Builds thick arm musculature." },
  { name: "Skullcrushers (EZ Bar)", muscleGroup: "Arms", secondaryMuscles: "Triceps long head", equipment: "EZ Bar", difficulty: "Intermediate", instructions: "Lie on bench. Hold EZ bar overhead arms extended. Lower bar toward forehead by bending elbows. Extend back up. Keep elbows pointing at ceiling throughout." },
  { name: "Preacher Curls", muscleGroup: "Arms", secondaryMuscles: "Brachialis", equipment: "EZ Bar", difficulty: "Intermediate", instructions: "Brace upper arms on preacher bench. Curl bar up toward shoulder. Squeeze bicep at top. Lower to full stretch. Isolates biceps by preventing elbow movement." },
  { name: "Tricep Dips (Bench)", muscleGroup: "Arms", secondaryMuscles: "Chest, Shoulders", equipment: "Bench", difficulty: "Beginner", instructions: "Hands on bench behind you with legs straight. Dip down by bending elbows. Lower until upper arms are parallel to floor. Push through palms to extend. Keep elbows close." },
  { name: "Concentration Curls", muscleGroup: "Arms", secondaryMuscles: "Bicep peak", equipment: "Dumbbells", difficulty: "Beginner", instructions: "Sit on bench. Brace elbow on inner thigh. Curl dumbbell to shoulder. Squeeze hard at top. Lower fully. Maximizes bicep peak contraction." },
  { name: "Overhead Tricep Extension", muscleGroup: "Arms", secondaryMuscles: "Tricep long head", equipment: "Dumbbell", difficulty: "Intermediate", instructions: "Hold dumbbell overhead with both hands. Lower behind head by bending elbows. Extend arms fully overhead. Excellent for stretching the long head of triceps." },
  { name: "Cable Bicep Curls", muscleGroup: "Arms", secondaryMuscles: "Forearms", equipment: "Cable Machine", difficulty: "Beginner", instructions: "Hold cable bar at hip level. Curl toward shoulder with constant cable tension. Superior to dumbbells for maintaining tension at bottom position. Lower slowly." },
  { name: "Close-Grip Chin-Ups", muscleGroup: "Arms", secondaryMuscles: "Back, Biceps", equipment: "Pull-Up Bar", difficulty: "Intermediate", instructions: "Supinated grip, hands shoulder-width. Pull up explosively. Squeeze biceps at top. Lower slowly. Works biceps much more than regular pull-ups." },
  { name: "Incline Dumbbell Curls", muscleGroup: "Arms", secondaryMuscles: "Bicep long head", equipment: "Dumbbells", difficulty: "Intermediate", instructions: "Sit on incline bench. Let arms hang straight. Curl from fully stretched position. Increased range of motion targets long head. Excellent for peak development." },
  { name: "Rope Tricep Pushdowns", muscleGroup: "Arms", secondaryMuscles: "Forearms", equipment: "Cable Machine", difficulty: "Beginner", instructions: "Use rope attachment. At bottom, flare hands outward while extending. Greater contraction than bar. Squeeze hard at full extension. Great medial head activation." },
  { name: "Zottman Curls", muscleGroup: "Arms", secondaryMuscles: "Brachioradialis, Forearms", equipment: "Dumbbells", difficulty: "Intermediate", instructions: "Curl up with supinated grip. Rotate to pronated grip at top. Lower with overhand grip. Curl up again and repeat. Works all curling muscles through full range." },
  { name: "Spider Curls", muscleGroup: "Arms", secondaryMuscles: "Bicep short head", equipment: "Barbell", difficulty: "Intermediate", instructions: "Lie face down on incline bench. Let arms hang. Curl bar from full extension. Vertical arm position maximizes tension through entire range. Builds bicep peak." },
  { name: "Cross-Body Hammer Curls", muscleGroup: "Arms", secondaryMuscles: "Brachialis", equipment: "Dumbbells", difficulty: "Beginner", instructions: "Curl dumbbell across body toward opposite shoulder. Emphasizes brachialis and brachioradialis more than standard hammer curl. Alternate arms." },
  { name: "Tricep Kickbacks", muscleGroup: "Arms", secondaryMuscles: "Rear Delts", equipment: "Dumbbells", difficulty: "Beginner", instructions: "Hinge at hips. Upper arm parallel to floor. Extend forearm behind you to full lockout. Squeeze at top. Lower slowly. Isolates all three tricep heads." },
  { name: "Cable Hammer Curls (Rope)", muscleGroup: "Arms", secondaryMuscles: "Brachioradialis", equipment: "Cable Machine", difficulty: "Beginner", instructions: "Use rope at low cable. Curl with neutral grip to shoulder. Constant cable tension throughout. Pull elbows back at top. Excellent forearm and brachialis builder." },
  { name: "Reverse Curls", muscleGroup: "Arms", secondaryMuscles: "Brachioradialis, Forearms", equipment: "Barbell", difficulty: "Beginner", instructions: "Grip barbell overhand. Curl toward shoulder. Primarily hits forearms and brachioradialis. Balances bicep development and improves wrist strength." },
  { name: "21s (Bicep Curls)", muscleGroup: "Arms", secondaryMuscles: "Brachialis", equipment: "Barbell", difficulty: "Intermediate", instructions: "7 reps lower half only, 7 reps upper half only, then 7 full reps without rest. Extreme time under tension. One of the best techniques for bicep pump and growth." },
  { name: "Diamond Push-Ups", muscleGroup: "Arms", secondaryMuscles: "Chest, Shoulders", equipment: "Bodyweight", difficulty: "Intermediate", instructions: "Form diamond shape with thumbs and forefingers touching. Lower chest to hands. Push back up. Keeps elbows close. Maximum tricep engagement of any push-up variation." },

  // ─── CORE ────────────────────────────────────────────────────────────────
  { name: "Plank", muscleGroup: "Core", secondaryMuscles: "Shoulders, Glutes", equipment: "Bodyweight", difficulty: "Beginner", instructions: "Forearms on floor, body in straight line. Brace all muscles — abs, glutes, quads. Hold position. Do not let hips sag or rise. Breathe normally throughout." },
  { name: "Cable Crunches", muscleGroup: "Core", secondaryMuscles: "Hip Flexors", equipment: "Cable Machine", difficulty: "Intermediate", instructions: "Kneel facing cable machine. Rope behind neck. Crunch down by flexing spine. Touch elbows to thighs. Return up slowly. Heavy loading possible. Best weighted ab exercise." },
  { name: "Ab Wheel Rollout", muscleGroup: "Core", secondaryMuscles: "Lats, Shoulders", equipment: "Ab Wheel", difficulty: "Advanced", instructions: "Kneel with ab wheel. Roll forward as far as possible keeping core braced. Use abs to pull wheel back. Do not let lower back hyperextend. The king of ab exercises." },
  { name: "Hanging Leg Raises", muscleGroup: "Core", secondaryMuscles: "Hip Flexors", equipment: "Pull-Up Bar", difficulty: "Intermediate", instructions: "Hang from bar. Raise legs to horizontal or higher. Control the descent. Do not swing. Lower abs and hip flexors are primary movers. Full range of motion." },
  { name: "Russian Twists", muscleGroup: "Core", secondaryMuscles: "Obliques", equipment: "Plate", difficulty: "Intermediate", instructions: "Sit with feet slightly elevated. Hold weight at chest. Rotate torso side to side. Touch weight to floor each side. Keep chest tall. Targets obliques heavily." },
  { name: "Dead Bug", muscleGroup: "Core", secondaryMuscles: "Hip Flexors", equipment: "Bodyweight", difficulty: "Beginner", instructions: "Lie on back. Extend opposite arm and leg. Keep lower back pressed to floor. Return and alternate. Spinal anti-extension. Safe and highly effective core exercise." },
  { name: "Mountain Climbers", muscleGroup: "Core", secondaryMuscles: "Shoulders, Hip Flexors", equipment: "Bodyweight", difficulty: "Beginner", instructions: "High plank position. Drive knees to chest alternately. Keep hips level. Move quickly for conditioning or slowly for control. Full core engagement throughout." },
  { name: "Bicycle Crunches", muscleGroup: "Core", secondaryMuscles: "Obliques", equipment: "Bodyweight", difficulty: "Beginner", instructions: "Lie on back, hands behind head. Bring opposite elbow to knee while extending other leg. Rotate fully each rep. Do not pull neck. Best oblique exercise." },
  { name: "Side Plank", muscleGroup: "Core", secondaryMuscles: "Obliques, Glutes", equipment: "Bodyweight", difficulty: "Beginner", instructions: "Rest on forearm and side of foot. Keep body in straight line. Hold position. Can add hip dips for extra challenge. Targets lateral core and obliques." },
  { name: "Dragon Flag", muscleGroup: "Core", secondaryMuscles: "Lats, Hip Flexors", equipment: "Bench", difficulty: "Advanced", instructions: "Lie on bench. Grip bench behind head. Raise body to vertical. Lower slowly as one rigid unit. Do not collapse at hips. Bruce Lee's signature core exercise." },
  { name: "Hollow Body Hold", muscleGroup: "Core", secondaryMuscles: "Hip Flexors", equipment: "Bodyweight", difficulty: "Intermediate", instructions: "Lie on back. Raise arms overhead and legs off floor. Press lower back into floor. Hold position. Foundation of gymnastics. Pure anterior core tension." },
  { name: "V-Ups", muscleGroup: "Core", secondaryMuscles: "Hip Flexors", equipment: "Bodyweight", difficulty: "Intermediate", instructions: "Lie flat. Simultaneously raise arms and legs to meet at top forming V shape. Lower with control. Touch toes at top. Dynamic full range core exercise." },
  { name: "Pallof Press", muscleGroup: "Core", secondaryMuscles: "Obliques, Shoulders", equipment: "Cable Machine", difficulty: "Intermediate", instructions: "Stand sideways to cable. Hold handle at chest. Press cable forward without rotating. Return to chest. Anti-rotation exercise that prevents spine rotation under load." },
  { name: "Windshield Wipers", muscleGroup: "Core", secondaryMuscles: "Obliques, Lats", equipment: "Pull-Up Bar", difficulty: "Advanced", instructions: "Hang from bar. Raise legs to bar. Rotate legs side to side like windshield wipers. Control the rotation. Extreme oblique and hip flexor challenge." },
  { name: "L-Sit", muscleGroup: "Core", secondaryMuscles: "Hip Flexors, Triceps", equipment: "Parallel Bars", difficulty: "Advanced", instructions: "Support on parallel bars or dip bars. Hold legs straight and horizontal. Keep everything tight. Hold position. Incredible static core and hip flexor strength." },
  { name: "Reverse Crunches", muscleGroup: "Core", secondaryMuscles: "Hip Flexors", equipment: "Bodyweight", difficulty: "Beginner", instructions: "Lie on back. Bring knees to chest while lifting hips off floor. Lower slowly. Targets lower abs more than standard crunch. Keep lower back pressed to floor." },
  { name: "Landmine Rotations", muscleGroup: "Core", secondaryMuscles: "Obliques, Shoulders", equipment: "Barbell", difficulty: "Intermediate", instructions: "Hold end of landmine barbell with arms extended. Rotate from side to side in controlled arc. Brace core throughout. Excellent rotational power development." },
  { name: "Plank Hip Dips", muscleGroup: "Core", secondaryMuscles: "Obliques", equipment: "Bodyweight", difficulty: "Beginner", instructions: "Start in side plank. Dip hip to touch floor. Return to plank. Dynamic oblique activation while maintaining spinal stability. Great side plank progression." },
  { name: "Toes to Bar", muscleGroup: "Core", secondaryMuscles: "Hip Flexors, Lats", equipment: "Pull-Up Bar", difficulty: "Advanced", instructions: "Hang from pull-up bar. Raise straight legs to touch bar. Lower with control. Do not swing. Maximum hip flexor and lower ab challenge. Common in CrossFit." },
  { name: "Weighted Sit-Ups", muscleGroup: "Core", secondaryMuscles: "Hip Flexors", equipment: "Plate", difficulty: "Intermediate", instructions: "Hold plate at chest. Perform full sit-up from floor to upright. Lower slowly with abs controlling descent. Adds progressive overload to the basic sit-up pattern." },

  // ─── CARDIO ──────────────────────────────────────────────────────────────
  { name: "Treadmill Running", muscleGroup: "Cardio", secondaryMuscles: "Legs, Core", equipment: "Treadmill", difficulty: "Beginner", instructions: "Set treadmill to comfortable pace. Land midfoot, not heel. Keep posture upright with slight lean. Swing arms naturally. Start with brisk walk and progress to run." },
  { name: "Cycling (Stationary Bike)", muscleGroup: "Cardio", secondaryMuscles: "Legs", equipment: "Stationary Bike", difficulty: "Beginner", instructions: "Adjust seat so knee is slightly bent at bottom. Pedal at smooth, consistent cadence. Keep upper body relaxed. Low impact, joint-friendly cardio option." },
  { name: "Jump Rope", muscleGroup: "Cardio", secondaryMuscles: "Calves, Shoulders, Core", equipment: "Jump Rope", difficulty: "Intermediate", instructions: "Jump with both feet or alternate feet. Land softly on balls of feet. Turn rope with wrists not arms. Start with 30 second intervals. Excellent conditioning tool." },
  { name: "Burpees", muscleGroup: "Cardio", secondaryMuscles: "Chest, Shoulders, Legs, Core", equipment: "Bodyweight", difficulty: "Advanced", instructions: "Start standing. Jump down to push-up position. Perform push-up. Jump feet forward. Jump explosively with hands overhead. Full body explosive exercise." },
  { name: "HIIT Sprints", muscleGroup: "Cardio", secondaryMuscles: "Legs, Core", equipment: "Treadmill", difficulty: "Intermediate", instructions: "Alternate 30 seconds maximum effort sprint with 60 seconds recovery walk. Repeat 8-10 times. Most time-efficient fat burning protocol. High intensity." },
  { name: "Rowing Machine", muscleGroup: "Cardio", secondaryMuscles: "Back, Arms, Legs", equipment: "Rowing Machine", difficulty: "Intermediate", instructions: "Push with legs first, then lean back, then pull with arms. Return in reverse order. Keep back straight. Best cardio machine for full body engagement." },
  { name: "Stair Climber", muscleGroup: "Cardio", secondaryMuscles: "Glutes, Quads, Calves", equipment: "Stair Climber", difficulty: "Intermediate", instructions: "Step at consistent pace. Do not lean heavily on rails. Use full foot on each step. Excellent glute and leg cardio. Harder than it looks." },
  { name: "Elliptical Trainer", muscleGroup: "Cardio", secondaryMuscles: "Legs, Arms", equipment: "Elliptical", difficulty: "Beginner", instructions: "Match stride to elliptical path. Push and pull handles. Keep upright posture. Zero impact on joints. Ideal for injury recovery or low-impact cardio training." },
  { name: "Box Jumps", muscleGroup: "Cardio", secondaryMuscles: "Legs, Core", equipment: "Plyo Box", difficulty: "Intermediate", instructions: "Stand in front of box. Jump onto box landing in squat position. Stand fully. Step down carefully. Develops explosive power and cardiovascular fitness." },
  { name: "Battle Ropes", muscleGroup: "Cardio", secondaryMuscles: "Shoulders, Core, Arms", equipment: "Battle Ropes", difficulty: "Intermediate", instructions: "Alternate arms in wave pattern. Keep stance wide and low. Maintain fast pace. Alternatively slam both ropes simultaneously. 30-second intervals are brutal." },
  { name: "Assault Bike (Air Bike)", muscleGroup: "Cardio", secondaryMuscles: "Legs, Arms, Shoulders", equipment: "Assault Bike", difficulty: "Intermediate", instructions: "Push pedals and pull-push handles simultaneously. More resistance equals more speed. Do 20 second all-out efforts. The hardest cardio machine in the gym." },
  { name: "Swimming", muscleGroup: "Cardio", secondaryMuscles: "Full Body", equipment: "Pool", difficulty: "Intermediate", instructions: "Choose any stroke — freestyle is most efficient. Focus on breathing pattern. Turn head to breathe, not body. Develop efficient technique for best results." },
  { name: "Kettlebell Swings", muscleGroup: "Cardio", secondaryMuscles: "Glutes, Back, Shoulders", equipment: "Kettlebell", difficulty: "Intermediate", instructions: "Hinge at hips not squat. Drive hips explosively forward. Let kettlebell float to shoulder height. Hike back between legs. Hip power, not arms. Excellent conditioning." },
  { name: "Jump Squats", muscleGroup: "Cardio", secondaryMuscles: "Legs, Glutes", equipment: "Bodyweight", difficulty: "Intermediate", instructions: "Start in squat position. Jump explosively, extending through hips. Land softly in squat position absorbing impact. Develops leg power and conditioning." },
  { name: "Versa Climber", muscleGroup: "Cardio", secondaryMuscles: "Arms, Legs, Core", equipment: "Versa Climber", difficulty: "Advanced", instructions: "Alternate arm and leg movement like climbing. Full range of motion. Extremely high calorie burn. One of the most demanding cardio machines available." },
  { name: "Ski Erg", muscleGroup: "Cardio", secondaryMuscles: "Lats, Core, Legs", equipment: "Ski Erg", difficulty: "Intermediate", instructions: "Pull both handles down from overhead to hips. Hinge at hips as you pull. Return handles overhead. Mimics cross-country skiing. Great upper body cardio." },
  { name: "Sled Push", muscleGroup: "Cardio", secondaryMuscles: "Legs, Core, Shoulders", equipment: "Sled", difficulty: "Advanced", instructions: "Grip sled at hip height, arms extended. Drive sled forward with powerful leg strides. Keep torso at 45 degrees. Short explosive distances. Ultimate conditioning." },
  { name: "Incline Treadmill Walk", muscleGroup: "Cardio", secondaryMuscles: "Glutes, Calves", equipment: "Treadmill", difficulty: "Beginner", instructions: "Set incline to 12-15%. Walk at 3mph for 30-45 minutes. Do not hold rails. Highly effective low-impact fat burning protocol. 12-3-30 viral method." },
  { name: "Plyometric Lunges", muscleGroup: "Cardio", secondaryMuscles: "Legs, Core", equipment: "Bodyweight", difficulty: "Intermediate", instructions: "Start in lunge position. Jump and switch legs in air. Land in opposite lunge. Keep front knee over ankle. Develops leg power and raises heart rate rapidly." },
  { name: "Jump Rope Double-Unders", muscleGroup: "Cardio", secondaryMuscles: "Calves, Wrists", equipment: "Jump Rope", difficulty: "Advanced", instructions: "Jump higher than single-under. Turn rope twice under feet per jump. Requires timing and coordination. Much more demanding than standard jump rope." },

  // ─── FULL BODY ────────────────────────────────────────────────────────────
  { name: "Barbell Deadlift (Full Body)", muscleGroup: "Full Body", secondaryMuscles: "Back, Legs, Core, Grip", equipment: "Barbell", difficulty: "Advanced", instructions: "The king of all exercises. Hinge at hips. Keep spine neutral. Drive through floor. Lock hips at top. Trains virtually every muscle in the body in one movement." },
  { name: "Clean and Press", muscleGroup: "Full Body", secondaryMuscles: "Legs, Back, Shoulders, Arms", equipment: "Barbell", difficulty: "Advanced", instructions: "Pull bar from floor explosively. Catch in rack position. Press overhead. Return to floor. Two powerful movements combined. Excellent athletic strength builder." },
  { name: "Thrusters", muscleGroup: "Full Body", secondaryMuscles: "Legs, Shoulders, Core", equipment: "Barbell", difficulty: "Advanced", instructions: "Hold bar at shoulders. Squat down. Drive up explosively and press bar overhead. One fluid movement. The signature CrossFit exercise. Brutal conditioning." },
  { name: "Kettlebell Windmill", muscleGroup: "Full Body", secondaryMuscles: "Shoulders, Obliques, Hamstrings", equipment: "Kettlebell", difficulty: "Advanced", instructions: "Hold kettlebell overhead. Push hips to side of lifted arm. Hinge to touch floor with free hand. Return to standing. Requires stability, mobility, and strength." },
  { name: "Turkish Get-Up", muscleGroup: "Full Body", secondaryMuscles: "Shoulders, Core, Hips", equipment: "Kettlebell", difficulty: "Advanced", instructions: "Lie holding kettlebell overhead. Rise to standing in controlled sequence. Reverse to return to floor. One of the most complete strength and mobility exercises ever." },
  { name: "Man Makers", muscleGroup: "Full Body", secondaryMuscles: "Chest, Back, Shoulders, Legs", equipment: "Dumbbells", difficulty: "Advanced", instructions: "Push-up, row each arm, squat to press. All in one fluid movement. Comprehensive full body conditioning exercise. One rep is humbling. Used in HIIT circuits." },
  { name: "Devil's Press", muscleGroup: "Full Body", secondaryMuscles: "Chest, Shoulders, Back, Legs", equipment: "Dumbbells", difficulty: "Advanced", instructions: "Burpee with dumbbells. Swing them overhead at the top instead of jumping. Combines power, strength, and endurance. One of the hardest full body exercises." },
  { name: "Bear Complex", muscleGroup: "Full Body", secondaryMuscles: "Full Body", equipment: "Barbell", difficulty: "Advanced", instructions: "Power clean, front squat, push press, back squat, push press — all without bar leaving hands. 5 reps counts as one set. Devastating metabolic strength workout." },
  { name: "Dumbbell Complex", muscleGroup: "Full Body", secondaryMuscles: "Full Body", equipment: "Dumbbells", difficulty: "Intermediate", instructions: "Curl, press, squat, deadlift performed in sequence without rest. Flows continuously using same dumbbells. Excellent for time-efficient total body training." },
  { name: "Sandbag Carry", muscleGroup: "Full Body", secondaryMuscles: "Core, Grip, Legs", equipment: "Sandbag", difficulty: "Intermediate", instructions: "Hold sandbag in bear hug or over shoulder. Walk for specified distance or time. Odd object training builds functional strength. Core must work constantly." },
  { name: "Barbell Complex (Cosgrove)", muscleGroup: "Full Body", secondaryMuscles: "Full Body", equipment: "Barbell", difficulty: "Advanced", instructions: "Deadlift, Romanian deadlift, row, power clean, front squat, push press — 6 reps each without racking bar. Iconic fat-loss and conditioning complex." },
  { name: "Kettlebell Clean and Press", muscleGroup: "Full Body", secondaryMuscles: "Legs, Back, Shoulders", equipment: "Kettlebell", difficulty: "Intermediate", instructions: "Clean kettlebell to rack position. Press overhead. Lower with control. Clean again. Powerful ballistic movement followed by grind. Excellent strength and power." },
  { name: "Power Snatch", muscleGroup: "Full Body", secondaryMuscles: "Legs, Back, Shoulders", equipment: "Barbell", difficulty: "Advanced", instructions: "Wide grip on bar. Explosive pull from floor. Drive under bar as it rises. Catch overhead with arms locked. Most technically demanding barbell exercise." },
  { name: "Squat to Press (Thruster with DB)", muscleGroup: "Full Body", secondaryMuscles: "Legs, Shoulders, Core", equipment: "Dumbbells", difficulty: "Intermediate", instructions: "Hold dumbbells at shoulders. Squat to parallel. Drive up explosively and press dumbbells overhead in one motion. Lower back to shoulders. Repeat." },
  { name: "Renegade Row to Push-Up", muscleGroup: "Full Body", secondaryMuscles: "Chest, Back, Core", equipment: "Dumbbells", difficulty: "Advanced", instructions: "In push-up position with dumbbells. Row one arm, then push-up, then row other arm. Count as one rep. Full body anti-rotation and pressing combination." },
  { name: "Pull-Up to Muscle-Up", muscleGroup: "Full Body", secondaryMuscles: "Chest, Shoulders, Triceps", equipment: "Pull-Up Bar", difficulty: "Advanced", instructions: "Pull explosively above bar into push-up position. Transition chest over bar. Press to full extension. Requires explosive pull strength and tricep lockout. Advanced calisthenics." },
  { name: "Rope Climb", muscleGroup: "Full Body", secondaryMuscles: "Back, Biceps, Core", equipment: "Rope", difficulty: "Advanced", instructions: "Jump and grab rope. Pull with arms while locking with legs. Alternate hand over hand while using legs for power. Descend slowly. Builds incredible upper body pulling strength." },
  { name: "Deadball Slam", muscleGroup: "Full Body", secondaryMuscles: "Core, Shoulders, Hips", equipment: "Medicine Ball", difficulty: "Intermediate", instructions: "Pick up heavy medicine ball. Raise overhead. Slam powerfully to ground. Pick up and repeat. Maximum power output. Excellent stress-relief exercise too." },
  { name: "Tire Flip", muscleGroup: "Full Body", secondaryMuscles: "Legs, Back, Shoulders, Core", equipment: "Tire", difficulty: "Advanced", instructions: "Dig fingers under tire. Drive with legs as you push tire up. At 45 degrees, switch to push position. Flip tire over. Functional strongman exercise. Pure power." },
  { name: "Farmer's Walk (Heavy)", muscleGroup: "Full Body", secondaryMuscles: "Traps, Core, Forearms, Legs", equipment: "Dumbbells", difficulty: "Intermediate", instructions: "Pick up heaviest dumbbells you can hold. Walk with tall posture and controlled steps. Maximum full body tension. Simple but brutally effective strength builder." },
];

async function seedExercises() {
  console.log(`Seeding ${exercises.length} exercises...`);

  await db.execute(sql`DELETE FROM exercises`);

  const chunkSize = 50;
  for (let i = 0; i < exercises.length; i += chunkSize) {
    const chunk = exercises.slice(i, i + chunkSize);
    await db.insert(exercisesTable).values(chunk);
    console.log(`Inserted ${Math.min(i + chunkSize, exercises.length)} / ${exercises.length}`);
  }

  console.log("Done! All exercises seeded successfully.");
  process.exit(0);
}

seedExercises().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
